export default {
  "0972e27f": [() => import(/* webpackChunkName: "0972e27f" */ "@site/docs/vscode-bridge.md"), "@site/docs/vscode-bridge.md", require.resolveWeak("@site/docs/vscode-bridge.md")],
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "22dd74f7": [() => import(/* webpackChunkName: "22dd74f7" */ "@generated/docusaurus-plugin-content-docs/default/p/index-466.json"), "@generated/docusaurus-plugin-content-docs/default/p/index-466.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/index-466.json")],
  "3b8c55ea": [() => import(/* webpackChunkName: "3b8c55ea" */ "@site/docs/installation.md"), "@site/docs/installation.md", require.resolveWeak("@site/docs/installation.md")],
  "3f0c9c29": [() => import(/* webpackChunkName: "3f0c9c29" */ "@site/docs/ci.md"), "@site/docs/ci.md", require.resolveWeak("@site/docs/ci.md")],
  "5281b7a2": [() => import(/* webpackChunkName: "5281b7a2" */ "@site/docs/architecture.md"), "@site/docs/architecture.md", require.resolveWeak("@site/docs/architecture.md")],
  "541d0f3e": [() => import(/* webpackChunkName: "541d0f3e" */ "@site/docs/workflows/visual-overlay.md"), "@site/docs/workflows/visual-overlay.md", require.resolveWeak("@site/docs/workflows/visual-overlay.md")],
  "55453002": [() => import(/* webpackChunkName: "55453002" */ "@site/docs/figma-integration.md"), "@site/docs/figma-integration.md", require.resolveWeak("@site/docs/figma-integration.md")],
  "5bde2c62": [() => import(/* webpackChunkName: "5bde2c62" */ "@site/docs/workflows/compare-elements.md"), "@site/docs/workflows/compare-elements.md", require.resolveWeak("@site/docs/workflows/compare-elements.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "9c5703a9": [() => import(/* webpackChunkName: "9c5703a9" */ "@site/docs/tailwind.md"), "@site/docs/tailwind.md", require.resolveWeak("@site/docs/tailwind.md")],
  "9d9f8394": [() => import(/* webpackChunkName: "9d9f8394" */ "@site/docs/troubleshooting.md"), "@site/docs/troubleshooting.md", require.resolveWeak("@site/docs/troubleshooting.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "f269fb21": [() => import(/* webpackChunkName: "f269fb21" */ "@site/docs/design-tokens.md"), "@site/docs/design-tokens.md", require.resolveWeak("@site/docs/design-tokens.md")],};
